version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mongo:4.0.0
      - image: circleci/postgres:9.6.2-alpine

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - deps-{{ .Branch }}-
            - deps-

      - run:
          name: Wait for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Install Ginkgo
          command: go get github.com/onsi/ginkgo/ginkgo

      - run:
          name: Get dependencies
          command: go mod download

      - run:
          name: Run tests
          command: make coverage-ci

      - run: bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - store_test_results:
          path: test-results
